// tests/windows-shim-heartbeat.test.cjs — Windows pre-launcher silent-hang net
//
// Locks the three defenses added to eliminate the "sillye hangs with no
// output" class on Windows:
//
//   A. install.ps1 $cmdContent writes a batch shim that
//        * prints a heartbeat + node path under SILLY_TRACE_BOOT=1
//        * probes `where node` and exits 127 with an actionable message
//          (ALWAYS on — not gated behind SILLY_TRACE_BOOT)
//        * propagates Node exit code via %_exit% / exit /b
//
//   B. every bin/*.js entry shim arms a 5s `_preBootTimer` (unref'd) that
//      exits 43 with a fatal message if the launcher module never loads,
//      and a try/catch around the dynamic import that exits 44 on any
//      synchronous import error.
//
//   C. install.ps1 runs a self-smoke at the end of install (sillye.cmd
//      --version) so any boot-time breakage surfaces at install time.
//
// Together these cover every frame between cmd.exe handing off to the .cmd
// shim and silly-launcher.js reaching its in-module 30s watchdog. See
// bin/CLAUDE.md §"Silent-hang safety net".

'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BIN = path.join(ROOT, 'bin');

console.log('Windows shim heartbeat tests\n');

// ── 1. install.ps1 cmdContent heartbeat contract ──
//
// Both the source-of-truth (installer/install.ps1) and the mirrored root
// copy (install.ps1, regenerated by .github/workflows/sync-installer.yml)
// must carry the same heartbeat template. We lock both files.

function readInstallPs1(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), 'utf8');
}

(function testCmdContentHasHeartbeat() {
  for (const relPath of ['installer/install.ps1', 'install.ps1']) {
    const src = readInstallPs1(relPath);

    // SILLY_TRACE_BOOT=1 gates the heartbeat echo lines
    assert.ok(
      /if\s+"%SILLY_TRACE_BOOT%"=="1"/.test(src),
      `${relPath}: cmdContent must check %SILLY_TRACE_BOOT%=="1" for heartbeat`
    );
    // Timestamped shim entry line
    assert.ok(
      /\[silly-boot \+0ms shim\].*%time%/.test(src),
      `${relPath}: cmdContent must echo "[silly-boot +0ms shim] ... %time%" for visible boot evidence`
    );
    // Heartbeat writes to stderr, not stdout (avoid polluting adapter pipe)
    assert.ok(
      /\[silly-boot \+0ms shim\][^\n]*1>&2/.test(src),
      `${relPath}: cmdContent shim heartbeat must redirect to stderr (1>&2)`
    );
    // Exit-code trace line
    assert.ok(
      /\[silly-boot shim\] node exited code=%_exit%/.test(src),
      `${relPath}: cmdContent must echo node exit code for trace chain completeness`
    );
  }
  console.log('  cmdContent SILLY_TRACE_BOOT heartbeat (both install.ps1 copies): PASS');
})();

(function testCmdContentWhereNodeCheck() {
  for (const relPath of ['installer/install.ps1', 'install.ps1']) {
    const src = readInstallPs1(relPath);

    // where-node probe is ALWAYS-on (must NOT be gated behind SILLY_TRACE_BOOT)
    assert.ok(
      /where node >nul 2>&1/.test(src),
      `${relPath}: cmdContent must probe \`where node\` before spawning node`
    );
    // Actionable FATAL message
    assert.ok(
      /\[silly\]\[FATAL\][^\n]*'node' not found in PATH/.test(src),
      `${relPath}: cmdContent missing actionable [silly][FATAL] 'node' not found message`
    );
    // Pointer to install URL
    assert.ok(
      /nodejs\.org/.test(src),
      `${relPath}: cmdContent FATAL message should point users at nodejs.org`
    );
    // Exit code 127 is the stable "command not found" convention
    assert.ok(
      /exit \/b 127/.test(src),
      `${relPath}: cmdContent where-node fail path must exit 127 (POSIX "command not found")`
    );
  }
  console.log('  cmdContent where-node FATAL check (both install.ps1 copies): PASS');
})();

(function testCmdContentExitPropagation() {
  for (const relPath of ['installer/install.ps1', 'install.ps1']) {
    const src = readInstallPs1(relPath);
    assert.ok(
      /set _exit=%errorlevel%/.test(src),
      `${relPath}: cmdContent must capture Node's exit code into %_exit%`
    );
    assert.ok(
      /exit \/b %_exit%/.test(src),
      `${relPath}: cmdContent must propagate %_exit% so $LASTEXITCODE is correct`
    );
  }
  console.log('  cmdContent exit-code propagation: PASS');
})();

// ── 2. Entry-shim pre-launcher watchdog contract ──
//
// The 5s _preBootTimer + FATAL message + exit-code contract (43/44) all
// live in the shared helper `bin/_entry-preamble.js` (extracted so 5 shims
// stop duplicating ~25 lines each). The shims themselves are now 3-line
// delegators that call `runEntry('<target>'[, { skipPermissions: true }])`.
//
// Shim-level asserts: delegation shape + correct target command.
// Preamble-level asserts: every invariant that previously lived per-shim.

const SHIMS = [
  { file: 'silly.js',   target: 'silly',  skip: false },
  { file: 'sillyx.js',  target: 'sillyx', skip: false },
  { file: 'sillye.js',  target: 'sillye', skip: false },
  { file: 'sillyxs.js', target: 'sillyx', skip: true  },
  { file: 'sillyes.js', target: 'sillye', skip: true  },
];
const PREAMBLE = '_entry-preamble.js';

(function testEntryShimDelegation() {
  for (const { file, target, skip } of SHIMS) {
    const src = fs.readFileSync(path.join(BIN, file), 'utf8');

    // Each shim imports runEntry from the shared preamble.
    assert.ok(
      /import\s*\{\s*runEntry\s*\}\s*from\s*['"]\.\/_entry-preamble\.js['"]/.test(src),
      `bin/${file}: must import { runEntry } from './_entry-preamble.js'`
    );
    // Each shim invokes runEntry with the correct target command.
    const callRe = new RegExp(
      `await\\s+runEntry\\(\\s*['"]${target}['"]` +
      (skip ? `\\s*,\\s*\\{\\s*skipPermissions\\s*:\\s*true\\s*\\}` : '') +
      `\\s*\\)`
    );
    assert.ok(
      callRe.test(src),
      `bin/${file}: must call runEntry('${target}'${skip ? ", { skipPermissions: true }" : ''}) — regex ${callRe}`
    );
    // Shim stays tiny — refactor gain is lost if someone starts inlining
    // logic back into shims. 10 lines is generous (shebang + import + await
    // call; <=5 non-blank lines in current form).
    const loc = src.split('\n').filter(l => l.trim().length > 0).length;
    assert.ok(
      loc <= 10,
      `bin/${file}: entry shim must stay <=10 non-blank lines (got ${loc}) — any real logic belongs in _entry-preamble.js`
    );
  }
  console.log(`  Entry-shim delegation contract (${SHIMS.length} shims): PASS`);
})();

(function testPreamblePreBootTimer() {
  const src = fs.readFileSync(path.join(BIN, PREAMBLE), 'utf8');

  // Timer declaration — setTimeout with 5s deadline
  assert.ok(
    /const\s+_preBootTimer\s*=\s*setTimeout\(/.test(src),
    `bin/${PREAMBLE}: missing _preBootTimer setTimeout declaration`
  );
  assert.ok(
    /5_?000/.test(src),
    `bin/${PREAMBLE}: _preBootTimer must use 5000ms (5s) deadline`
  );
  // unref() is mandatory — without it the 5s timer blocks clean exit paths
  assert.ok(
    /_preBootTimer\.unref\(\)/.test(src),
    `bin/${PREAMBLE}: _preBootTimer must .unref() so clean boots do not block`
  );
  // Exit 43 is the "launcher-load hang" contract (distinct from
  // silly-launcher.js exit 42 "in-launcher watchdog fired")
  assert.ok(
    /process\.exit\(43\)/.test(src),
    `bin/${PREAMBLE}: _preBootTimer must process.exit(43) — stable contract`
  );
  // Exit 44 is the "launcher import threw" contract
  assert.ok(
    /process\.exit\(44\)/.test(src),
    `bin/${PREAMBLE}: launcher import catch must process.exit(44) — stable contract`
  );
  // Timer is cleared on both success and failure paths — without clear,
  // the 5s deadline still fires (unref'd so it wouldn't block exit) but
  // the trace signal becomes misleading
  const clearCount = (src.match(/clearTimeout\(_preBootTimer\)/g) || []).length;
  assert.ok(
    clearCount >= 2,
    `bin/${PREAMBLE}: clearTimeout(_preBootTimer) must appear on both success + failure paths (got ${clearCount})`
  );
  // Try/catch wraps the import
  assert.ok(
    /try\s*\{[^}]*await\s+import/s.test(src),
    `bin/${PREAMBLE}: await import must be wrapped in try/catch for exit-44 path`
  );
  // runEntry must be ESM-exported — shims consume it via `import { runEntry }`
  assert.ok(
    /export\s+async\s+function\s+runEntry\s*\(/.test(src),
    `bin/${PREAMBLE}: must export async function runEntry (shims use \`await runEntry(...)\`)`
  );
  // skipPermissions option must splice --dangerously-skip-permissions into argv
  assert.ok(
    /process\.argv\.splice\(\s*2\s*,\s*0\s*,\s*['"]--dangerously-skip-permissions['"]\s*\)/.test(src),
    `bin/${PREAMBLE}: skipPermissions branch must splice --dangerously-skip-permissions into argv`
  );
  // SILLY_TARGET_COMMAND must be set from the helper arg so downstream
  // launcher resolution still sees the right target.
  assert.ok(
    /process\.env\.SILLY_TARGET_COMMAND\s*=\s*targetCommand/.test(src),
    `bin/${PREAMBLE}: must assign process.env.SILLY_TARGET_COMMAND = targetCommand`
  );
  console.log(`  Preamble _preBootTimer contract: PASS`);
})();

(function testPreambleFatalMessage() {
  const src = fs.readFileSync(path.join(BIN, PREAMBLE), 'utf8');
  // Actionable diagnostic text
  assert.ok(
    /\[silly\]\[FATAL\]/.test(src),
    `bin/${PREAMBLE}: _preBootTimer must print a [silly][FATAL] line`
  );
  assert.ok(
    /SILLY_TRACE_BOOT/.test(src),
    `bin/${PREAMBLE}: _preBootTimer message must point users at SILLY_TRACE_BOOT=1`
  );
  assert.ok(
    /launcher import failed/.test(src),
    `bin/${PREAMBLE}: catch branch must print "launcher import failed" for disambiguation from timer fire`
  );
  console.log(`  Preamble FATAL message content: PASS`);
})();

// ── 3. install.ps1 self-smoke test ──

(function testInstallSelfSmoke() {
  for (const relPath of ['installer/install.ps1', 'install.ps1']) {
    const src = readInstallPs1(relPath);
    // The self-smoke invokes sillye.cmd --version (picks a quick-exit
    // subcommand so we don't spawn the real TUI)
    assert.ok(
      /sillye\.cmd['"]?\s+--version/.test(src),
      `${relPath}: self-smoke must invoke sillye.cmd --version`
    );
    // Check exit code — without it a crashed shim is silently "OK". Accept
    // either direct `$LASTEXITCODE -ne 0` branching or the defensive form
    // `$smokeCode = $LASTEXITCODE` + `$smokeCode -ne 0` (required when
    // wrapping the call in try/catch to defang NativeCommandError under
    // SILLY_TRACE_BOOT=1 sessions — see install-ps1-self-smoke.test.cjs).
    assert.ok(
      /\$LASTEXITCODE\s+-ne\s+0/.test(src) ||
        (/\$smokeCode\s*=\s*\$LASTEXITCODE/.test(src) && /\$smokeCode\s+-ne\s+0/.test(src)),
      `${relPath}: self-smoke must branch on $LASTEXITCODE (direct or via $smokeCode)`
    );
    // Fallback instruction references SILLY_TRACE_BOOT
    assert.ok(
      /SILLY_TRACE_BOOT/.test(src),
      `${relPath}: self-smoke fail branch must point users at SILLY_TRACE_BOOT=1`
    );
  }
  console.log('  install.ps1 self-smoke test (both copies): PASS');
})();

console.log('\nAll windows-shim-heartbeat tests passed.');
